/*
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
 */

package project.pkg2;

/**
 *
 * @author Nick
 */
public class Project2 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int i = 1;
        int temp = 0;
        int total = 0;
        
        while(i < 4000000) {
            i += temp;
            temp = i - temp;
            if(i % 2 == 0) // if even, add to total
               total += i;
        }
        System.out.println(total);
    }
    
}
